// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# Azure Data Lake Storage provides storage for Hadoop and other big data workloads.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl) returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # List Filesystems
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK 
    remote isolated function listFilesystems(ListFilesystemsHeaders headers = {}, *ListFilesystemsQueries queries) returns FilesystemList|error {
        string resourcePath = string `/`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # List Paths
    #
    # + filesystem - The filesystem identifier.  The value must start and end with a letter or number and must contain only letters, numbers, and the dash (-) character.  Consecutive dashes are not permitted.  All letters must be lowercase.  The value must have between 3 and 63 characters
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Ok 
    remote isolated function listPaths(string filesystem, ListPathsHeaders headers = {}, *ListPathsQueries queries) returns PathList|error {
        string resourcePath = string `/${getEncodedUri(filesystem)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create Filesystem
    #
    # + filesystem - The filesystem identifier.  The value must start and end with a letter or number and must contain only letters, numbers, and the dash (-) character.  Consecutive dashes are not permitted.  All letters must be lowercase.  The value must have between 3 and 63 characters
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Created 
    remote isolated function createFilesystem(string filesystem, CreateFilesystemHeaders headers = {}, *CreateFilesystemQueries queries) returns error? {
        string resourcePath = string `/${getEncodedUri(filesystem)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Delete Filesystem
    #
    # + filesystem - The filesystem identifier.  The value must start and end with a letter or number and must contain only letters, numbers, and the dash (-) character.  Consecutive dashes are not permitted.  All letters must be lowercase.  The value must have between 3 and 63 characters
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Accepted 
    remote isolated function deleteFilesystem(string filesystem, DeleteFilesystemHeaders headers = {}, *DeleteFilesystemQueries queries) returns error? {
        string resourcePath = string `/${getEncodedUri(filesystem)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Set Filesystem Properties
    #
    # + filesystem - The filesystem identifier.  The value must start and end with a letter or number and must contain only letters, numbers, and the dash (-) character.  Consecutive dashes are not permitted.  All letters must be lowercase.  The value must have between 3 and 63 characters
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Ok 
    remote isolated function setFilesystemProperties(string filesystem, SetFilesystemPropertiesHeaders headers = {}, *SetFilesystemPropertiesQueries queries) returns error? {
        string resourcePath = string `/${getEncodedUri(filesystem)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        return self.clientEp->patch(resourcePath, request, httpHeaders);
    }

    # Get Filesystem Properties.
    #
    # + filesystem - The filesystem identifier.  The value must start and end with a letter or number and must contain only letters, numbers, and the dash (-) character.  Consecutive dashes are not permitted.  All letters must be lowercase.  The value must have between 3 and 63 characters
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Ok 
    remote isolated function getFilesystemProperties(string filesystem, GetFilesystemPropertiesHeaders headers = {}, *GetFilesystemPropertiesQueries queries) returns http:Response|error {
        string resourcePath = string `/${getEncodedUri(filesystem)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->head(resourcePath, httpHeaders);
    }

    # Read File
    #
    # + filesystem - The filesystem identifier
    # + path - The file or directory path
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Ok 
    remote isolated function readFile(string filesystem, string path, ReadFileHeaders headers = {}, *ReadFileQueries queries) returns byte[]|error {
        string resourcePath = string `/${getEncodedUri(filesystem)}/${getEncodedUri(path)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create File | Create Directory | Rename File | Rename Directory
    #
    # + filesystem - The filesystem identifier
    # + path - The file or directory path
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The file or directory was created 
    remote isolated function createPath(string filesystem, string path, CreatePathHeaders headers = {}, *CreatePathQueries queries) returns error? {
        string resourcePath = string `/${getEncodedUri(filesystem)}/${getEncodedUri(path)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Lease Path
    #
    # + filesystem - The filesystem identifier
    # + path - The file or directory path
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The "renew", "change" or "release" action was successful 
    remote isolated function leasePath(string filesystem, string path, LeasePathHeaders headers, *LeasePathQueries queries) returns error? {
        string resourcePath = string `/${getEncodedUri(filesystem)}/${getEncodedUri(path)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Delete File | Delete Directory
    #
    # + filesystem - The filesystem identifier
    # + path - The file or directory path
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The file was deleted 
    remote isolated function deletePath(string filesystem, string path, DeletePathHeaders headers = {}, *DeletePathQueries queries) returns error? {
        string resourcePath = string `/${getEncodedUri(filesystem)}/${getEncodedUri(path)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Append Data | Flush Data | Set Properties | Set Access Control
    #
    # + filesystem - The filesystem identifier
    # + path - The file or directory path
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Valid only for append operations.  The data to be uploaded and appended to the file 
    # + return - The data was flushed (written) to the file or the properties were set successfully 
    remote isolated function updatePath(string filesystem, string path, byte[] payload, UpdatePathHeaders headers = {}, *UpdatePathQueries queries) returns error? {
        string resourcePath = string `/${getEncodedUri(filesystem)}/${getEncodedUri(path)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        request.setPayload(payload, "application/octet-stream");
        return self.clientEp->patch(resourcePath, request, httpHeaders);
    }

    # Get Properties | Get Status | Get Access Control List | Check Access
    #
    # + filesystem - The filesystem identifier
    # + path - The file or directory path
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns all properties for the file or directory 
    remote isolated function getPathProperties(string filesystem, string path, GetPathPropertiesHeaders headers = {}, *GetPathPropertiesQueries queries) returns http:Response|error {
        string resourcePath = string `/${getEncodedUri(filesystem)}/${getEncodedUri(path)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->head(resourcePath, httpHeaders);
    }
}
