// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/http;

# Represents the Queries record for the operation: readFile
public type ReadFileQueries record {
    # An optional operation timeout value in seconds. The period begins when the request is received by the service. If the timeout value elapses before the operation completes, the operation fails
    @constraint:Int {minValue: 1}
    int:Signed32 timeout?;
};

# Represents the Queries record for the operation: leasePath
public type LeasePathQueries record {
    # An optional operation timeout value in seconds. The period begins when the request is received by the service. If the timeout value elapses before the operation completes, the operation fails
    @constraint:Int {minValue: 1}
    int:Signed32 timeout?;
};

# Represents the Headers record for the operation: getFilesystemProperties
public type GetFilesystemPropertiesHeaders record {
    # Specifies the version of the REST protocol used for processing the request. Required for every authorized request, including those that use a Microsoft Entra ID bearer token. Defaults to 2019-10-31
    @http:Header {name: "x-ms-version"}
    string xMsVersion = "2019-10-31";
    # Specifies the Coordinated Universal Time (UTC) for the request.  This is required when using shared key authorization
    @http:Header {name: "x-ms-date"}
    string xMsDate?;
    # A UUID recorded in the analytics logs for troubleshooting and correlation
    @http:Header {name: "x-ms-client-request-id"}
    string xMsClientRequestId?;
};

# Represents the Queries record for the operation: createPath
public type CreatePathQueries record {
    # Optional. Valid only when namespace is enabled. This parameter determines the behavior of the rename operation. The value must be "legacy" or "posix", and the default value will be "posix". 
    "legacy"|"posix" mode?;
    # Required only for Create File and Create Directory. The value must be "file" or "directory"
    "directory"|"file" 'resource?;
    # Optional.  When renaming a directory, the number of paths that are renamed with each invocation is limited.  If the number of paths to be renamed exceeds this limit, a continuation token is returned in this response header.  When a continuation token is returned in the response, it must be specified in a subsequent invocation of the rename operation to continue renaming the directory
    string continuation?;
    # An optional operation timeout value in seconds. The period begins when the request is received by the service. If the timeout value elapses before the operation completes, the operation fails
    @constraint:Int {minValue: 1}
    int:Signed32 timeout?;
};

# Represents the Headers record for the operation: readFile
public type ReadFileHeaders record {
    # Optional.  An ETag value or the special wildcard ("*") value. Specify this header to perform the operation only if the resource's ETag does not match the value specified. The ETag must be specified in quotes
    @http:Header {name: "If-None-Match"}
    string ifNoneMatch?;
    # Specifies the version of the REST protocol used for processing the request. Required for every authorized request, including those that use a Microsoft Entra ID bearer token. Defaults to 2019-10-31
    @http:Header {name: "x-ms-version"}
    string xMsVersion = "2019-10-31";
    # Optional.  An ETag value. Specify this header to perform the operation only if the resource's ETag matches the value specified. The ETag must be specified in quotes
    @http:Header {name: "If-Match"}
    string ifMatch?;
    # Specifies the Coordinated Universal Time (UTC) for the request.  This is required when using shared key authorization
    @http:Header {name: "x-ms-date"}
    string xMsDate?;
    # Optional. If this header is specified, the operation will be performed only if both of the following conditions are met: i) the path's lease is currently active and ii) the lease ID specified in the request matches that of the path
    @http:Header {name: "x-ms-lease-id"}
    string xMsLeaseId?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has been modified since the specified date and time
    @http:Header {name: "If-Modified-Since"}
    string ifModifiedSince?;
    # The HTTP Range request header specifies one or more byte ranges of the resource to be retrieved
    @http:Header {name: "Range"}
    string range?;
    # Optional. When this header is set to "true" and specified together with the Range header, the service returns the MD5 hash for the range, as long as the range is less than or equal to 4MB in size. If this header is specified without the Range header, the service returns status code 400 (Bad Request). If this header is set to true when the range exceeds 4 MB in size, the service returns status code 400 (Bad Request)
    @http:Header {name: "x-ms-range-get-content-md5"}
    boolean xMsRangeGetContentMd5?;
    # A UUID recorded in the analytics logs for troubleshooting and correlation
    @http:Header {name: "x-ms-client-request-id"}
    string xMsClientRequestId?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has not been modified since the specified date and time
    @http:Header {name: "If-Unmodified-Since"}
    string ifUnmodifiedSince?;
};

# Represents the Headers record for the operation: createPath
public type CreatePathHeaders record {
    # Optional and only valid if Hierarchical Namespace is enabled for the account. When creating a file or directory and the parent folder does not have a default ACL, the umask restricts the permissions of the file or directory to be created.  The resulting permission is given by p & ^u, where p is the permission and u is the umask.  For example, if p is 0777 and u is 0057, then the resulting permission is 0720.  The default permission is 0777 for a directory and 0666 for a file.  The default umask is 0027.  The umask must be specified in 4-digit octal notation (e.g. 0766)
    @http:Header {name: "x-ms-umask"}
    string xMsUmask?;
    # Optional for rename operations.  A lease ID for the source path.  The source path must have an active lease and the lease ID must match
    @http:Header {name: "x-ms-source-lease-id"}
    string xMsSourceLeaseId?;
    # Optional.  A lease ID for the path specified in the URI.  The path to be overwritten must have an active lease and the lease ID must match
    @http:Header {name: "x-ms-lease-id"}
    string xMsLeaseId?;
    # Optional. A date and time value. Specify this header to perform the rename operation only if the source has been modified since the specified date and time
    @http:Header {name: "x-ms-source-if-modified-since"}
    string xMsSourceIfModifiedSince?;
    # Optional.  User-defined properties to be stored with the file or directory, in the format of a comma-separated list of name and value pairs "n1=v1, n2=v2, ...", where each value is a base64 encoded string. Note that the string may only contain ASCII characters in the ISO-8859-1 character set
    @http:Header {name: "x-ms-properties"}
    string xMsProperties?;
    # Optional.  An ETag value. Specify this header to perform the rename operation only if the source's ETag matches the value specified. The ETag must be specified in quotes
    @http:Header {name: "x-ms-source-if-match"}
    string xMsSourceIfMatch?;
    # Optional. A date and time value. Specify this header to perform the rename operation only if the source has not been modified since the specified date and time
    @http:Header {name: "x-ms-source-if-unmodified-since"}
    string xMsSourceIfUnmodifiedSince?;
    # Optional.  The service stores this value and includes it in the "Cache-Control" response header for "Read File" operations
    @http:Header {name: "x-ms-cache-control"}
    string xMsCacheControl?;
    # Optional.  The service stores this value and includes it in the "Content-Language" response header for "Read File" operations
    @http:Header {name: "x-ms-content-language"}
    string xMsContentLanguage?;
    # Optional.  Specifies which content encodings have been applied to the file. This value is returned to the client when the "Read File" operation is performed
    @http:Header {name: "Content-Encoding"}
    string contentEncoding?;
    # Optional and only valid if Hierarchical Namespace is enabled for the account. Sets POSIX access permissions for the file owner, the file owning group, and others. Each class may be granted read, write, or execute permission.  The sticky bit is also supported.  Both symbolic (rwxrw-rw-) and 4-digit octal notation (e.g. 0766) are supported
    @http:Header {name: "x-ms-permissions"}
    string xMsPermissions?;
    # Specifies the version of the REST protocol used for processing the request. Required for every authorized request, including those that use a Microsoft Entra ID bearer token. Defaults to 2019-10-31
    @http:Header {name: "x-ms-version"}
    string xMsVersion = "2019-10-31";
    # An optional file or directory to be renamed.  The value must have the following format: "/{filesystem}/{path}".  If "x-ms-properties" is specified, the properties will overwrite the existing properties; otherwise, the existing properties will be preserved. This value must be a URL percent-encoded string. Note that the string may only contain ASCII characters in the ISO-8859-1 character set
    @http:Header {name: "x-ms-rename-source"}
    string xMsRenameSource?;
    # Optional.  The service stores this value and includes it in the "Content-Type" response header for "Read File" operations
    @http:Header {name: "x-ms-content-type"}
    string xMsContentType?;
    # Optional.  The service stores this value and includes it in the "Content-Encoding" response header for "Read File" operations
    @http:Header {name: "x-ms-content-encoding"}
    string xMsContentEncoding?;
    # Optional.  An ETag value or the special wildcard ("*") value. Specify this header to perform the operation only if the resource's ETag does not match the value specified. The ETag must be specified in quotes
    @http:Header {name: "If-None-Match"}
    string ifNoneMatch?;
    # Optional.  The service stores this value and includes it in the "Content-Disposition" response header for "Read File" operations
    @http:Header {name: "x-ms-content-disposition"}
    string xMsContentDisposition?;
    # Optional.  An ETag value. Specify this header to perform the operation only if the resource's ETag matches the value specified. The ETag must be specified in quotes
    @http:Header {name: "If-Match"}
    string ifMatch?;
    # Optional.  The service stores this value and includes it in the "Cache-Control" response header for "Read File" operations for "Read File" operations
    @http:Header {name: "Cache-Control"}
    string cacheControl?;
    # Specifies the Coordinated Universal Time (UTC) for the request.  This is required when using shared key authorization
    @http:Header {name: "x-ms-date"}
    string xMsDate?;
    # Optional.  The service stores this value and includes it in the "Content-Disposition" response header for "Read File" operations
    @http:Header {name: "Content-Disposition"}
    string contentDisposition?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has been modified since the specified date and time
    @http:Header {name: "If-Modified-Since"}
    string ifModifiedSince?;
    # Optional.  An ETag value or the special wildcard ("*") value. Specify this header to perform the rename operation only if the source's ETag does not match the value specified. The ETag must be specified in quotes
    @http:Header {name: "x-ms-source-if-none-match"}
    string xMsSourceIfNoneMatch?;
    # A UUID recorded in the analytics logs for troubleshooting and correlation
    @http:Header {name: "x-ms-client-request-id"}
    string xMsClientRequestId?;
    # Optional.  Specifies the natural language used by the intended audience for the file
    @http:Header {name: "Content-Language"}
    string contentLanguage?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has not been modified since the specified date and time
    @http:Header {name: "If-Unmodified-Since"}
    string ifUnmodifiedSince?;
};

# Represents the Headers record for the operation: listPaths
public type ListPathsHeaders record {
    # Specifies the version of the REST protocol used for processing the request. Required for every authorized request, including those that use a Microsoft Entra ID bearer token. Defaults to 2019-10-31
    @http:Header {name: "x-ms-version"}
    string xMsVersion = "2019-10-31";
    # Specifies the Coordinated Universal Time (UTC) for the request.  This is required when using shared key authorization
    @http:Header {name: "x-ms-date"}
    string xMsDate?;
    # A UUID recorded in the analytics logs for troubleshooting and correlation
    @http:Header {name: "x-ms-client-request-id"}
    string xMsClientRequestId?;
};

# Represents the Headers record for the operation: leasePath
public type LeasePathHeaders record {
    # Optional.  An ETag value or the special wildcard ("*") value. Specify this header to perform the operation only if the resource's ETag does not match the value specified. The ETag must be specified in quotes
    @http:Header {name: "If-None-Match"}
    string ifNoneMatch?;
    # Specifies the version of the REST protocol used for processing the request. Required for every authorized request, including those that use a Microsoft Entra ID bearer token. Defaults to 2019-10-31
    @http:Header {name: "x-ms-version"}
    string xMsVersion = "2019-10-31";
    # Optional.  An ETag value. Specify this header to perform the operation only if the resource's ETag matches the value specified. The ETag must be specified in quotes
    @http:Header {name: "If-Match"}
    string ifMatch?;
    # Required when "x-ms-lease-action" is "acquire" or "change".  A lease will be acquired with this lease ID if the operation is successful
    @http:Header {name: "x-ms-proposed-lease-id"}
    string xMsProposedLeaseId?;
    # The lease break period duration is optional to break a lease, and  specifies the break period of the lease in seconds.  The lease break  duration must be between 0 and 60 seconds
    @http:Header {name: "x-ms-lease-break-period"}
    int:Signed32 xMsLeaseBreakPeriod?;
    # Specifies the Coordinated Universal Time (UTC) for the request.  This is required when using shared key authorization
    @http:Header {name: "x-ms-date"}
    string xMsDate?;
    # Required when "x-ms-lease-action" is "renew", "change" or "release". For the renew and release actions, this must match the current lease ID
    @http:Header {name: "x-ms-lease-id"}
    string xMsLeaseId?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has been modified since the specified date and time
    @http:Header {name: "If-Modified-Since"}
    string ifModifiedSince?;
    # The lease duration is required to acquire a lease, and specifies the duration of the lease in seconds.  The lease duration must be between 15 and 60 seconds or -1 for infinite lease
    @http:Header {name: "x-ms-lease-duration"}
    int:Signed32 xMsLeaseDuration?;
    # There are five lease actions: "acquire", "break", "change", "renew", and "release". Use "acquire" and specify the "x-ms-proposed-lease-id" and "x-ms-lease-duration" to acquire a new lease. Use "break" to break an existing lease. When a lease is broken, the lease break period is allowed to elapse, during which time no lease operation except break and release can be performed on the file. When a lease is successfully broken, the response indicates the interval in seconds until a new lease can be acquired. Use "change" and specify the current lease ID in "x-ms-lease-id" and the new lease ID in "x-ms-proposed-lease-id" to change the lease ID of an active lease. Use "renew" and specify the "x-ms-lease-id" to renew an existing lease. Use "release" and specify the "x-ms-lease-id" to release a lease
    @http:Header {name: "x-ms-lease-action"}
    "acquire"|"break"|"change"|"renew"|"release" xMsLeaseAction;
    # A UUID recorded in the analytics logs for troubleshooting and correlation
    @http:Header {name: "x-ms-client-request-id"}
    string xMsClientRequestId?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has not been modified since the specified date and time
    @http:Header {name: "If-Unmodified-Since"}
    string ifUnmodifiedSince?;
};

# Represents the Queries record for the operation: deletePath
public type DeletePathQueries record {
    # Optional.  When deleting a directory, the number of paths that are deleted with each invocation is limited.  If the number of paths to be deleted exceeds this limit, a continuation token is returned in this response header.  When a continuation token is returned in the response, it must be specified in a subsequent invocation of the delete operation to continue deleting the directory
    string continuation?;
    # An optional operation timeout value in seconds. The period begins when the request is received by the service. If the timeout value elapses before the operation completes, the operation fails
    @constraint:Int {minValue: 1}
    int:Signed32 timeout?;
    # Required and valid only when the resource is a directory.  If "true", all paths beneath the directory will be deleted. If "false" and the directory is non-empty, an error occurs
    boolean recursive?;
};

# Represents the Queries record for the operation: getFilesystemProperties
public type GetFilesystemPropertiesQueries record {
    # The value must be "filesystem" for all filesystem operations
    "filesystem" 'resource;
    # An optional operation timeout value in seconds. The period begins when the request is received by the service. If the timeout value elapses before the operation completes, the operation fails
    @constraint:Int {minValue: 1}
    int:Signed32 timeout?;
};

# Represents the Headers record for the operation: deletePath
public type DeletePathHeaders record {
    # Optional.  An ETag value or the special wildcard ("*") value. Specify this header to perform the operation only if the resource's ETag does not match the value specified. The ETag must be specified in quotes
    @http:Header {name: "If-None-Match"}
    string ifNoneMatch?;
    # Specifies the version of the REST protocol used for processing the request. Required for every authorized request, including those that use a Microsoft Entra ID bearer token. Defaults to 2019-10-31
    @http:Header {name: "x-ms-version"}
    string xMsVersion = "2019-10-31";
    # Optional.  An ETag value. Specify this header to perform the operation only if the resource's ETag matches the value specified. The ETag must be specified in quotes
    @http:Header {name: "If-Match"}
    string ifMatch?;
    # Specifies the Coordinated Universal Time (UTC) for the request.  This is required when using shared key authorization
    @http:Header {name: "x-ms-date"}
    string xMsDate?;
    # The lease ID must be specified if there is an active lease
    @http:Header {name: "x-ms-lease-id"}
    string xMsLeaseId?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has been modified since the specified date and time
    @http:Header {name: "If-Modified-Since"}
    string ifModifiedSince?;
    # A UUID recorded in the analytics logs for troubleshooting and correlation
    @http:Header {name: "x-ms-client-request-id"}
    string xMsClientRequestId?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has not been modified since the specified date and time
    @http:Header {name: "If-Unmodified-Since"}
    string ifUnmodifiedSince?;
};

# Represents the Queries record for the operation: listPaths
public type ListPathsQueries record {
    # Optional. Valid only when Hierarchical Namespace is enabled for the account. If "true", the user identity values returned in the owner and group fields of each list entry will be transformed from Azure Active Directory Object IDs to User Principal Names.  If "false", the values will be returned as Azure Active Directory Object IDs. The default value is false. Note that group and application Object IDs are not translated because they do not have unique friendly names
    boolean upn?;
    # The value must be "filesystem" for all filesystem operations
    "filesystem" 'resource;
    # An optional value that specifies the maximum number of items to return. If omitted or greater than 5,000, the response will include up to 5,000 items
    @constraint:Int {minValue: 1}
    int:Signed32 maxResults?;
    # Filters results to paths within the specified directory. An error occurs if the directory does not exist
    string directory?;
    # The number of paths returned with each invocation is limited. If the number of paths to be returned exceeds this limit, a continuation token is returned in the response header x-ms-continuation. When a continuation token is  returned in the response, it must be specified in a subsequent invocation of the list operation to continue listing the paths
    string continuation?;
    # An optional operation timeout value in seconds. The period begins when the request is received by the service. If the timeout value elapses before the operation completes, the operation fails
    @constraint:Int {minValue: 1}
    int:Signed32 timeout?;
    # If "true", all paths are listed; otherwise, only paths at the root of the filesystem are listed.  If "directory" is specified, the list will only include paths that share the same root
    boolean recursive;
};

# Represents the Headers record for the operation: deleteFilesystem
public type DeleteFilesystemHeaders record {
    # Specifies the version of the REST protocol used for processing the request. Required for every authorized request, including those that use a Microsoft Entra ID bearer token. Defaults to 2019-10-31
    @http:Header {name: "x-ms-version"}
    string xMsVersion = "2019-10-31";
    # Specifies the Coordinated Universal Time (UTC) for the request.  This is required when using shared key authorization
    @http:Header {name: "x-ms-date"}
    string xMsDate?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has been modified since the specified date and time
    @http:Header {name: "If-Modified-Since"}
    string ifModifiedSince?;
    # A UUID recorded in the analytics logs for troubleshooting and correlation
    @http:Header {name: "x-ms-client-request-id"}
    string xMsClientRequestId?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has not been modified since the specified date and time
    @http:Header {name: "If-Unmodified-Since"}
    string ifUnmodifiedSince?;
};

# A list of filesystems in the storage account
public type FilesystemList record {
    # List of filesystems
    Filesystem[] filesystems?;
};

# Represents the Queries record for the operation: deleteFilesystem
public type DeleteFilesystemQueries record {
    # The value must be "filesystem" for all filesystem operations
    "filesystem" 'resource;
    # An optional operation timeout value in seconds. The period begins when the request is received by the service. If the timeout value elapses before the operation completes, the operation fails
    @constraint:Int {minValue: 1}
    int:Signed32 timeout?;
};

# A filesystem in the storage account
public type Filesystem record {
    # The name of the filesystem
    string name?;
    # The entity tag (ETag) of the filesystem
    string eTag?;
    # The date and time the filesystem was last modified, in RFC 1123 format
    string lastModified?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# A file or directory in a filesystem
public type Path record {
    # The owner of the file or directory
    string owner?;
    # The POSIX access permissions for the owner, the owning group and others
    string permissions?;
    # The path of the file or directory, relative to the filesystem root
    string name?;
    # The entity tag (ETag) of the path
    string eTag?;
    # The size of the file in bytes
    int contentLength?;
    # The date and time the path was last modified, in RFC 1123 format
    string lastModified?;
    # Whether the path is a directory
    boolean isDirectory = false;
    # The owning group of the file or directory
    string group?;
};

# Represents the Queries record for the operation: updatePath
public type UpdatePathQueries record {
    # The action must be "append" to upload data to be appended to a file, "flush" to flush previously uploaded data to a file, "setProperties" to set the properties of a file or directory, or "setAccessControl" to set the owner, group, permissions, or access control list for a file or directory.  Note that Hierarchical Namespace must be enabled for the account in order to use access control.  Also note that the Access Control List (ACL) includes permissions for the owner, owning group, and others, so the x-ms-permissions and x-ms-acl request headers are mutually exclusive
    "append"|"flush"|"setProperties"|"setAccessControl" action;
    # Valid only for flush operations.  If "true", uncommitted data is retained after the flush operation completes; otherwise, the uncommitted data is deleted after the flush operation.  The default is false.  Data at offsets less than the specified position are written to the file when flush succeeds, but this optional parameter allows data after the flush position to be retained for a future flush operation
    boolean retainUncommittedData?;
    # This parameter allows the caller to upload data in parallel and control the order in which it is appended to the file.  It is required when uploading data to be appended to the file and when flushing previously uploaded data to the file.  The value must be the position where the data is to be appended.  Uploaded data is not immediately flushed, or written, to the file.  To flush, the previously uploaded data must be contiguous, the position parameter must be specified and equal to the length of the file after all data has been written, and there must not be a request entity body included with the request
    int position?;
    # Azure Storage Events allow applications to receive notifications when files change. When Azure Storage Events are enabled, a file changed event is raised. This event has a property indicating whether this is the final change to distinguish the difference between an intermediate flush to a file stream and the final close of a file stream. The close query parameter is valid only when the action is "flush" and change notifications are enabled. If the value of close is "true" and the flush operation completes successfully, the service raises a file change notification with a property indicating that this is the final update (the file stream has been closed). If "false" a change notification is raised indicating the file has changed. The default is false. This query parameter is set to true by the Hadoop ABFS driver to indicate that the file stream has been closed."
    boolean close?;
    # An optional operation timeout value in seconds. The period begins when the request is received by the service. If the timeout value elapses before the operation completes, the operation fails
    @constraint:Int {minValue: 1}
    int:Signed32 timeout?;
};

# Represents the Headers record for the operation: getPathProperties
public type GetPathPropertiesHeaders record {
    # Optional.  An ETag value or the special wildcard ("*") value. Specify this header to perform the operation only if the resource's ETag does not match the value specified. The ETag must be specified in quotes
    @http:Header {name: "If-None-Match"}
    string ifNoneMatch?;
    # Specifies the version of the REST protocol used for processing the request. Required for every authorized request, including those that use a Microsoft Entra ID bearer token. Defaults to 2019-10-31
    @http:Header {name: "x-ms-version"}
    string xMsVersion = "2019-10-31";
    # Optional.  An ETag value. Specify this header to perform the operation only if the resource's ETag matches the value specified. The ETag must be specified in quotes
    @http:Header {name: "If-Match"}
    string ifMatch?;
    # Specifies the Coordinated Universal Time (UTC) for the request.  This is required when using shared key authorization
    @http:Header {name: "x-ms-date"}
    string xMsDate?;
    # Optional. If this header is specified, the operation will be performed only if both of the following conditions are met: i) the path's lease is currently active and ii) the lease ID specified in the request matches that of the path
    @http:Header {name: "x-ms-lease-id"}
    string xMsLeaseId?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has been modified since the specified date and time
    @http:Header {name: "If-Modified-Since"}
    string ifModifiedSince?;
    # A UUID recorded in the analytics logs for troubleshooting and correlation
    @http:Header {name: "x-ms-client-request-id"}
    string xMsClientRequestId?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has not been modified since the specified date and time
    @http:Header {name: "If-Unmodified-Since"}
    string ifUnmodifiedSince?;
};

# Represents the Queries record for the operation: getPathProperties
public type GetPathPropertiesQueries record {
    # Optional. Valid only when Hierarchical Namespace is enabled for the account. If "true", the user identity values returned in the x-ms-owner, x-ms-group, and x-ms-acl response headers will be transformed from Azure Active Directory Object IDs to User Principal Names.  If "false", the values will be returned as Azure Active Directory Object IDs. The default value is false. Note that group and application Object IDs are not translated because they do not have unique friendly names
    boolean upn?;
    # Optional. If the value is "getStatus" only the system defined properties for the path are returned. If the value is "getAccessControl" the access control list is returned in the response headers (Hierarchical Namespace must be enabled for the account), otherwise the properties are returned
    "getAccessControl"|"getStatus"|"checkAccess" action?;
    # Required only for check access action. Valid only when Hierarchical Namespace is enabled for the account. File system operation read/write/execute in string form, matching regex pattern '[rwx-]{3}'
    string fsAction?;
    # An optional operation timeout value in seconds. The period begins when the request is received by the service. If the timeout value elapses before the operation completes, the operation fails
    @constraint:Int {minValue: 1}
    int:Signed32 timeout?;
};

# A list of paths in a filesystem
public type PathList record {
    # List of paths
    Path[] paths?;
};

# Represents the Headers record for the operation: setFilesystemProperties
public type SetFilesystemPropertiesHeaders record {
    # Specifies the version of the REST protocol used for processing the request. Required for every authorized request, including those that use a Microsoft Entra ID bearer token. Defaults to 2019-10-31
    @http:Header {name: "x-ms-version"}
    string xMsVersion = "2019-10-31";
    # Specifies the Coordinated Universal Time (UTC) for the request.  This is required when using shared key authorization
    @http:Header {name: "x-ms-date"}
    string xMsDate?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has been modified since the specified date and time
    @http:Header {name: "If-Modified-Since"}
    string ifModifiedSince?;
    # Optional. User-defined properties to be stored with the filesystem, in the format of a comma-separated list of name and value pairs "n1=v1, n2=v2, ...", where each value is a base64 encoded string. Note that the string may only contain ASCII characters in the ISO-8859-1 character set.  If the filesystem exists, any properties not included in the list will be removed.  All properties are removed if the header is omitted.  To merge new and existing properties, first get all existing properties and the current E-Tag, then make a conditional request with the E-Tag and include values for all properties
    @http:Header {name: "x-ms-properties"}
    string xMsProperties?;
    # A UUID recorded in the analytics logs for troubleshooting and correlation
    @http:Header {name: "x-ms-client-request-id"}
    string xMsClientRequestId?;
    # Optional. A date and time value. Specify this header to perform the operation only if the resource has not been modified since the specified date and time
    @http:Header {name: "If-Unmodified-Since"}
    string ifUnmodifiedSince?;
};

# Represents the Headers record for the operation: updatePath
public type UpdatePathHeaders record {
    # Optional and valid only for the setAccessControl operation. Sets the owning group of the file or directory
    @http:Header {name: "x-ms-group"}
    string xMsGroup?;
    # Specifies the version of the REST protocol used for processing the request. Required for every authorized request, including those that use a Microsoft Entra ID bearer token. Defaults to 2019-10-31
    @http:Header {name: "x-ms-version"}
    string xMsVersion = "2019-10-31";
    # The lease ID must be specified if there is an active lease
    @http:Header {name: "x-ms-lease-id"}
    string xMsLeaseId?;
    # Optional and valid only for the setAccessControl operation. Sets POSIX access control rights on files and directories. The value is a comma-separated list of access control entries that fully replaces the existing access control list (ACL).  Each access control entry (ACE) consists of a scope, a type, a user or group identifier, and permissions in the format "[scope:][type]:[id]:[permissions]". The scope must be "default" to indicate the ACE belongs to the default ACL for a directory; otherwise scope is implicit and the ACE belongs to the access ACL.  There are four ACE types: "user" grants rights to the owner or a named user, "group" grants rights to the owning group or a named group, "mask" restricts rights granted to named users and the members of groups, and "other" grants rights to all users not found in any of the other entries. The user or group identifier is omitted for entries of type "mask" and "other".  The user or group identifier is also omitted for the owner and owning group.  The permission field is a 3-character sequence where the first character is 'r' to grant read access, the second character is 'w' to grant write access, and the third character is 'x' to grant execute permission.  If access is not granted, the '-' character is used to denote that the permission is denied. For example, the following ACL grants read, write, and execute rights to the file owner and john.doe@contoso, the read right to the owning group, and nothing to everyone else: "user::rwx,user:john.doe@contoso:rwx,group::r--,other::---,mask=rwx". Invalid in conjunction with x-ms-permissions
    @http:Header {name: "x-ms-acl"}
    string xMsAcl?;
    # Optional and only valid for "Flush & Set Properties" operations.  The service stores this value and includes it in the "Content-Md5" response header for "Read & Get Properties" operations. If this property is not specified on the request, then the property will be cleared for the file. Subsequent calls to "Read & Get Properties" will not return this property unless it is explicitly set on that file again
    @http:Header {name: "x-ms-content-md5"}
    string xMsContentMd5?;
    # Optional.  User-defined properties to be stored with the file or directory, in the format of a comma-separated list of name and value pairs "n1=v1, n2=v2, ...", where each value is a base64 encoded string. Note that the string may only contain ASCII characters in the ISO-8859-1 character set. Valid only for the setProperties operation. If the file or directory exists, any properties not included in the list will be removed.  All properties are removed if the header is omitted.  To merge new and existing properties, first get all existing properties and the current E-Tag, then make a conditional request with the E-Tag and include values for all properties
    @http:Header {name: "x-ms-properties"}
    string xMsProperties?;
    # Optional and only valid for flush and set properties operations.  The service stores this value and includes it in the "Content-Type" response header for "Read File" operations
    @http:Header {name: "x-ms-content-type"}
    string xMsContentType?;
    # Optional. An MD5 hash of the request content. This header is valid on "Append" and "Flush" operations. This hash is used to verify the integrity of the request content during transport. When this header is specified, the storage service compares the hash of the content that has arrived with this header value. If the two hashes do not match, the operation will fail with error code 400 (Bad Request). Note that this MD5 hash is not stored with the file. This header is associated with the request content, and not with the stored content of the file itself
    @http:Header {name: "Content-MD5"}
    string contentMD5?;
    # Optional and only valid for flush and set properties operations.  The service stores this value and includes it in the "Content-Encoding" response header for "Read File" operations
    @http:Header {name: "x-ms-content-encoding"}
    string xMsContentEncoding?;
    # Optional for Flush Data and Set Properties, but invalid for Append Data.  An ETag value or the special wildcard ("*") value. Specify this header to perform the operation only if the resource's ETag does not match the value specified. The ETag must be specified in quotes
    @http:Header {name: "If-None-Match"}
    string ifNoneMatch?;
    # Optional and only valid for flush and set properties operations.  The service stores this value and includes it in the "Content-Disposition" response header for "Read File" operations
    @http:Header {name: "x-ms-content-disposition"}
    string xMsContentDisposition?;
    # Optional for Flush Data and Set Properties, but invalid for Append Data.  An ETag value. Specify this header to perform the operation only if the resource's ETag matches the value specified. The ETag must be specified in quotes
    @http:Header {name: "If-Match"}
    string ifMatch?;
    # Optional and only valid for flush and set properties operations.  The service stores this value and includes it in the "Cache-Control" response header for "Read File" operations
    @http:Header {name: "x-ms-cache-control"}
    string xMsCacheControl?;
    # Specifies the Coordinated Universal Time (UTC) for the request.  This is required when using shared key authorization
    @http:Header {name: "x-ms-date"}
    string xMsDate?;
    # Optional and only valid for flush and set properties operations.  The service stores this value and includes it in the "Content-Language" response header for "Read File" operations
    @http:Header {name: "x-ms-content-language"}
    string xMsContentLanguage?;
    # Optional for Flush Data and Set Properties, but invalid for Append Data. A date and time value. Specify this header to perform the operation only if the resource has been modified since the specified date and time
    @http:Header {name: "If-Modified-Since"}
    string ifModifiedSince?;
    # Optional and only valid if Hierarchical Namespace is enabled for the account. Sets POSIX access permissions for the file owner, the file owning group, and others. Each class may be granted read, write, or execute permission.  The sticky bit is also supported.  Both symbolic (rwxrw-rw-) and 4-digit octal notation (e.g. 0766) are supported. Invalid in conjunction with x-ms-acl
    @http:Header {name: "x-ms-permissions"}
    string xMsPermissions?;
    # Required for "Append Data" and "Flush Data".  Must be 0 for "Flush Data".  Must be the length of the request content in bytes for "Append Data"
    @http:Header {name: "Content-Length"}
    int contentLength?;
    # A UUID recorded in the analytics logs for troubleshooting and correlation
    @http:Header {name: "x-ms-client-request-id"}
    string xMsClientRequestId?;
    # Optional and valid only for the setAccessControl operation. Sets the owner of the file or directory
    @http:Header {name: "x-ms-owner"}
    string xMsOwner?;
    # Optional for Flush Data and Set Properties, but invalid for Append Data. A date and time value. Specify this header to perform the operation only if the resource has not been modified since the specified date and time
    @http:Header {name: "If-Unmodified-Since"}
    string ifUnmodifiedSince?;
};

# Represents the Queries record for the operation: listFilesystems
public type ListFilesystemsQueries record {
    # The value must be "account" for all account operations
    "account" 'resource;
    # Filters results to filesystems within the specified prefix
    string prefix?;
    # An optional value that specifies the maximum number of items to return. If omitted or greater than 5,000, the response will include up to 5,000 items
    @constraint:Int {minValue: 1}
    int:Signed32 maxResults?;
    # The number of filesystems returned with each invocation is limited. If the number of filesystems to be returned exceeds this limit, a continuation token is returned in the response header x-ms-continuation. When a continuation token is  returned in the response, it must be specified in a subsequent invocation of the list operation to continue listing the filesystems
    string continuation?;
    # An optional operation timeout value in seconds. The period begins when the request is received by the service. If the timeout value elapses before the operation completes, the operation fails
    @constraint:Int {minValue: 1}
    int:Signed32 timeout?;
};

# Represents the Queries record for the operation: setFilesystemProperties
public type SetFilesystemPropertiesQueries record {
    # The value must be "filesystem" for all filesystem operations
    "filesystem" 'resource;
    # An optional operation timeout value in seconds. The period begins when the request is received by the service. If the timeout value elapses before the operation completes, the operation fails
    @constraint:Int {minValue: 1}
    int:Signed32 timeout?;
};

# Represents the Queries record for the operation: createFilesystem
public type CreateFilesystemQueries record {
    # The value must be "filesystem" for all filesystem operations
    "filesystem" 'resource;
    # An optional operation timeout value in seconds. The period begins when the request is received by the service. If the timeout value elapses before the operation completes, the operation fails
    @constraint:Int {minValue: 1}
    int:Signed32 timeout?;
};

# Represents the Headers record for the operation: listFilesystems
public type ListFilesystemsHeaders record {
    # Specifies the version of the REST protocol used for processing the request. Required for every authorized request, including those that use a Microsoft Entra ID bearer token. Defaults to 2019-10-31
    @http:Header {name: "x-ms-version"}
    string xMsVersion = "2019-10-31";
    # Specifies the Coordinated Universal Time (UTC) for the request.  This is required when using shared key authorization
    @http:Header {name: "x-ms-date"}
    string xMsDate?;
    # A UUID recorded in the analytics logs for troubleshooting and correlation
    @http:Header {name: "x-ms-client-request-id"}
    string xMsClientRequestId?;
};

# Represents the Headers record for the operation: createFilesystem
public type CreateFilesystemHeaders record {
    # Specifies the version of the REST protocol used for processing the request. Required for every authorized request, including those that use a Microsoft Entra ID bearer token. Defaults to 2019-10-31
    @http:Header {name: "x-ms-version"}
    string xMsVersion = "2019-10-31";
    # Specifies the Coordinated Universal Time (UTC) for the request.  This is required when using shared key authorization
    @http:Header {name: "x-ms-date"}
    string xMsDate?;
    # User-defined properties to be stored with the filesystem, in the format of a comma-separated list of name and value pairs "n1=v1, n2=v2, ...", where each value is a base64 encoded string. Note that the string may only contain ASCII characters in the ISO-8859-1 character set
    @http:Header {name: "x-ms-properties"}
    string xMsProperties?;
    # A UUID recorded in the analytics logs for troubleshooting and correlation
    @http:Header {name: "x-ms-client-request-id"}
    string xMsClientRequestId?;
};
